import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/About";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import WorkExperience from "../components/WorkExperience";
const Home: NextPage = () => {
  return (
    <div className="bg-[#252525] text-[#f2f2f2] scroll-smooth h-screen snap-y snap-mandatory overflow-scroll z-0">
      <Head>
        <title>Pavel&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header / Nav */}

      <Header />

      {/* Hero */}

      <section id="hero" className="snap-start">
        <Hero />
      </section>

      {/* About */}

      <section id="about" className="snap-center">
        <About />
      </section>

      {/* Experiance - no exp for now xd */}

      {/* <section id="experience" className="snap-center">
        <WorkExperience />
      </section> */}

      {/* Skills */}

      <section id="skills" className="snap-center">
        <Skills />
      </section>

      {/* Projects */}

      <section id="projects" className="snap-center">
        <Projects />
      </section>

      {/* Contact me */}
    </div>
  );
};

export default Home;
